import azarineSunscreen from "../assets/azarine-sunscreen.jpg";
import makeoverCushion from "../assets/makeover-cushion.jpg";
import makeoverLipcream from "../assets/makeover-lipcream.jpg";
import skintificCeramide from "../assets/skintific-moisturizer-ceramide.jpg";
import skintificNiacinamide from "../assets/skintific-moisturizer-niacinamide.jpg";
import somethincCleanser from "../assets/somethinc-cleanser.jpg";
import somethincCushion from "../assets/somethinc-cushion.jpg";
import somethincLipstick from "../assets/somethinc-lipstick.jpg";
import somethincVitC from "../assets/somethinc-vitc.jpg";
import wardahGlowCushion from "../assets/wardah-glow-cushion.jpg";
import wardahSunscreen from "../assets/wardah-sunscreen.jpg";
import wardahCushion from "../assets/wardahcushion.jpg";

export const products = [
  {
    id: 1,
    name: "Powerstay Sync Matte Cushion",
    brand: "MAKE OVER",
    slug: "make-over-powerstay-sync-matte-cushion",
    price: 239000,
    stock: 8,
    category: 1,
    category_name: "Makeup",
    rating: 4.8,
    img: makeoverCushion,
  },
  {
    id: 2,
    name: "Colorfit 5D Blur Cloud Cushion",
    brand: "WARDAH",
    slug: "wardah-colorfit-5d-blur-cloud-cushion",
    price: 149000,
    stock: 12,
    category: 1,
    category_name: "Makeup",
    rating: 4.7,
    img: wardahCushion,
  },
  {
    id: 3,
    name: "Hooman Breathable Cushion Cover",
    brand: "SOMETHINC",
    slug: "somethinc-hooman-breathable-cushion",
    price: 208000,
    stock: 5,
    category: 1,
    category_name: "Makeup",
    rating: 4.9,
    img: somethincCushion,
  },
  {
    id: 4,
    name: "Powerstay Transferproof Matte Lip Cream",
    brand: "MAKE OVER",
    slug: "make-over-powerstay-lip-cream",
    price: 143000,
    stock: 4,
    category: 1,
    category_name: "Makeup",
    rating: 4.8,
    img: makeoverLipcream,
  },
  {
    id: 5,
    name: "Checkmatte Transferproof Lipstick",
    brand: "SOMETHINC",
    slug: "somethinc-checkmatte-lipstick",
    price: 109000,
    stock: 9,
    category: 1,
    category_name: "Makeup",
    rating: 4.7,
    img: somethincLipstick,
  },
  {
    id: 6,
    name: "Colorfit Perfect Glow Cushion",
    brand: "WARDAH",
    slug: "wardah-colorfit-perfect-glow-cushion",
    price: 150000,
    stock: 7,
    category: 1,
    category_name: "Makeup",
    rating: 4.6,
    img: wardahGlowCushion,
  },

  {
    id: 7,
    name: "5X Ceramide Barrier Repair Moisture Gel",
    brand: "SKINTIFIC",
    slug: "skintific-5x-ceramide-moisture-gel",
    price: 139000,
    stock: 6,
    category: 2,
    category_name: "Skincare",
    rating: 4.9,
    img: skintificCeramide,
  },
  {
    id: 8,
    name: "MSH Niacinamide Brightening Moisture Gel",
    brand: "SKINTIFIC",
    slug: "skintific-niacinamide-moisture-gel",
    price: 149000,
    stock: 10,
    category: 2,
    category_name: "Skincare",
    rating: 4.8,
    img: skintificNiacinamide,
  },
  {
    id: 9,
    name: "Hydrasoothe Sunscreen Gel SPF45 PA++++",
    brand: "AZARINE",
    slug: "azarine-hydrasoothe-sunscreen",
    price: 59000,
    stock: 3,
    category: 2,
    category_name: "Skincare",
    rating: 4.9,
    img: azarineSunscreen,
  },
  {
    id: 10,
    name: "UV Shield Airy Smooth Sunscreen SPF50 PA++++",
    brand: "WARDAH",
    slug: "wardah-uv-shield-sunscreen",
    price: 99000,
    stock: 11,
    category: 2,
    category_name: "Skincare",
    rating: 4.8,
    img: wardahSunscreen,
  },
  {
    id: 11,
    name: "Glass-C 12% Vitamin C + GlutaBright Serum",
    brand: "SOMETHINC",
    slug: "somethinc-glass-c-vitamin-c",
    price: 249000,
    stock: 5,
    category: 2,
    category_name: "Skincare",
    rating: 4.8,
    img: somethincVitC,
  },
  {
    id: 12,
    name: "Low pH Gentle Jelly Cleanser",
    brand: "SOMETHINC",
    slug: "somethinc-low-ph-jelly-cleanser",
    price: 62000,
    stock: 14,
    category: 2,
    category_name: "Skincare",
    rating: 4.7,
    img: somethincCleanser,
  },
];